library(tidyverse)

## This set of graphs is intended to be created using the report generated by the 'Menu' -> 'Product Mix' selection on Toast

### FUNCTIONS + SETUP

## TODO - parse date from file dropped in here

find_file = function() {
  CSV_FILES = file.info(list.files(pattern = "(^pmix).*(\\.csv$)"))
  MOST_RECENT_CSV = rownames(CSV_FILES)[which.max(CSV_FILES$mtime)]
  
  
  ## WE'RE MAKING A LOT OF ASSUMPTIONS HERE
  ## assumed format: 'pmix_[startDate]-[endDate].csv'
  DATE_RANGE = substr(MOST_RECENT_CSV, 6, nchar(MOST_RECENT_CSV) - 4)
  
  list(most_recent_csv = MOST_RECENT_CSV, date_range = DATE_RANGE)
}

file_info = find_file()

const_setup = function(dateRange) {
  FILE_TYPE = ".pdf"
  FOLDER_NAME = paste("BBP_Report_Charts_",dateRange, sep = "")
  
  if(!file.exists(FOLDER_NAME)) {
    print(paste("Folder", FOLDER_NAME, "not found, creating..."))
    dir.create(FOLDER_NAME)
  }
  
  list(file_type = FILE_TYPE, output_folder = FOLDER_NAME)
}

consts = const_setup(file_info$date_range)

data_setup = function(fileName) {
  
  RAW_DATA = read.csv(fileName) %>%
    select(Item.ID, Parent.ID, Menu.Name, Menu.Group, Subgroup, Menu.Item, Item.Qty, Avg.Price, Net.Amount)
  
  ITEM_DATA = RAW_DATA %>%
    filter(Menu.Item != '' | !is.na(Parent.ID))
  
  GROUP_DATA = RAW_DATA %>% 
    filter(Menu.Group == '' & Menu.Name != "ALL MENUS")
  
  list(groups = GROUP_DATA, items = ITEM_DATA, raw = RAW_DATA)
}

data = data_setup(file_info$most_recent_csv)


all_plots = c()

plotBarGraph = function(bar_data, plot_title, x_var, x_lab, y_var, y_lab) {
  graph = ggplot(data=bar_data, aes(x=reorder(x_var, +y_var), y=y_var, fill=x_var)) + geom_bar(stat="identity") + theme_minimal()
  graph + coord_flip() + labs(x = x_lab, y = y_lab, title = plot_title) + theme(legend.position = "none")
}

savePlot = function(reportName, report) {
  output_file = paste(consts$output_folder, "/", reportName, consts$file_type, sep = "")
  
  # FUCK IT WE'RE OVERWRITING
  # inc = 1 
  # while(file.exists(output_file)) {
  #   print(paste("File", output_file, "exists, incrementing..."))
  #   output_file = paste(consts$output_folder, "/", reportName, "_", inc, consts$file_type, sep = "")
  #   inc = inc + 1
  # }
  
  ggsave(output_file, plot = report)
}

saveAllPlots = function(all) {
  output_file = paste(consts$output_folder, "/", "All_Graphs.pdf", sep="")
  pdf(output_file, onefile = TRUE)
  for(i in all){
    print(i)
  }
  dev.off()
}

## GROUP DATA
group_data_plot = plotBarGraph(bar_data = data$groups, 
                               plot_title = "Net Amount by Group",
                               x_var = data$groups$Menu.Name,
                               x_lab = "Group Name",
                               y_var = data$groups$Net.Amount, 
                               y_lab = "Net Amount")
savePlot(reportName = "Net_Amt_By_Group", report = group_data_plot)
all_plots = c(all_plots, group_data_plot)

## CAFE ITEM QTY
normal_cafe_menu = data$items %>%
  filter(Menu.Name == "Food" & Menu.Group %in% c("Breakfast", "Lunch"))

cafe_frequency_plot = plotBarGraph2(bar_data = normal_cafe_menu, 
                                   x_var = normal_cafe_menu$Menu.Item,
                                   x_lab = "Menu Item", 
                                   y_var = normal_cafe_menu$Item.Qty,
                                   y_lab = "Quantity Sold", 
                                   plot_title = "Cafe Purchases")
savePlot(reportName = "Cafe_Top_Sellers", report = cafe_frequency_plot)
all_plots = c(all_plots, cafe_frequency_plot)

## BEER 
beer_items = data$items %>%
  filter(Menu.Name == "Retail Beer")

beer_brand_top_sellers = beer_items %>%
    filter(Menu.Name == 'Retail Beer') %>%
    group_by(Menu.Group) %>%
    summarise(total_qty = sum(Item.Qty)) %>%
    filter(total_qty > 0) %>%
    arrange(desc(total_qty)) %>%
    head(n = 15)

beer_brand_frequency_plot = plotBarGraph(bar_data = beer_brand_top_sellers, 
                                         plot_title = "Beer Top Sellers by Brand",
                                         x_var = beer_brand_top_sellers$Menu.Group, 
                                         x_lab = "Brand",
                                         y_var = beer_brand_top_sellers$total_qty,
                                         y_lab = "Total Qty Sold")
savePlot(reportName = "Beer_Top_Sellers-Brand", report = beer_brand_frequency_plot)
all_plots = c(all_plots, beer_brand_frequency_plot)


## INDIVIDUAL TOP BEERS
beer_top_sellers = beer_items %>%
  arrange(desc(Item.Qty)) %>%
  head(n=15)

beer_ind_frequency_plot = plotBarGraph(bar_data = beer_top_sellers, 
                                       plot_title = "Beer Top Sellers by Can",
                                       x_var = beer_top_sellers$Menu.Item, 
                                       x_lab = "Beer",
                                       y_var = beer_top_sellers$Item.Qty,
                                       y_lab = "Total Qty Sold")
savePlot(reportName = "Beer_Top_Sellers-Can", report = beer_ind_frequency_plot)
all_plots = c(all_plots, beer_ind_frequency_plot)

## WINE SALES
wine_items = data$items %>%
  filter(Menu.Name == "Retail Wine")

wine_top_sellers = wine_items %>% 
  arrange(desc(Item.Qty)) %>%
  head(n=15)

wine_top_sellers_plot = plotBarGraph(bar_data = wine_top_sellers, 
                                     plot_title = "Wine Top Sellers by Bottle",
                                     x_var = paste(wine_top_sellers$Menu.Item, ", $", wine_top_sellers$Avg.Price, sep = ""),
                                     x_lab = "Wine",
                                     y_var = wine_top_sellers$Item.Qty, 
                                     y_lab = "Qty Sold")
savePlot(reportName = "Wine_Top_Sellers", report = wine_top_sellers_plot)
all_plots = c(all_plots, wine_top_sellers_plot)

wine_by_category = wine_items %>%
  filter(Avg.Price > 0) %>%
  group_by(gr=cut(Avg.Price, breaks=c(0,12,20,30,40,50,60,120))) %>%
  summarise(n= n(), net_amount = sum(Net.Amount)) %>%
  arrange(as.numeric(gr))

## it would be cool to get this as a multi-variable bar plot
## doing this manually because i want the things in order
wine_price_breakdown_plot = ggplot(data=wine_by_category, 
                                   aes(x=gr, 
                                       y=n, 
                                       fill=gr)) + geom_bar(stat="identity") + theme_minimal()
wine_price_breakdown_plot = wine_price_breakdown_plot + coord_flip() + labs(x = "Price Range", y = "Qty Sold", title = "Wine Sold by Price Bracket") + theme(legend.position = "none")
savePlot(reportName = "Wine_Sold_By_Price", report = wine_price_breakdown_plot)
all_plots = c(all_plots, wine_price_breakdown_plot)


## NON-ALCOHOLIC ITEMS

na_items = data$items %>%
  filter(Menu.Group == "N/A Bev") 

na_top_items = na_items %>%
  arrange(desc(Item.Qty)) %>%
  head(n=15)

na_top_items_plot = plotBarGraph(bar_data = na_top_items, 
                                 plot_title = "N/A Top Sellers",
                                 x_var = na_top_items$Menu.Item, 
                                 x_lab = "N/A Item",
                                 y_var = na_top_items$Item.Qty,
                                 y_lab = "Qty Sold")
savePlot(reportName = "NA_Top_Sellers", report = na_top_items_plot)
all_plots = c(all_plots, na_top_items_plot)

na_top_netters = na_items %>%
  arrange(desc(Net.Amount)) %>%
  head(n=15)

## it would be nice to find the margin for N/A or at least the costs :////
na_top_netters_plot = plotBarGraph(bar_data = na_top_netters, 
                                   plot_title = "N/A Top Netters",
                                   x_var = na_top_netters$Menu.Item, 
                                   x_lab = "N/A Item",
                                   y_var = na_top_netters$Net.Amount,
                                   y_lab = "Net Amount")
savePlot(reportName = "NA_Top_Netters", report = na_top_netters_plot)
all_plots = c(all_plots, na_top_netters_plot)

na_low_sales = na_items %>%
  filter(Item.Qty <= 2 & Item.Qty != 0)

View(na_low_sales)

## DELI
deli_items = data$items %>%
  filter(Menu.Name == "Deli")

deli_top_items = deli_items %>%
  arrange(desc(Item.Qty)) %>%
  head(n=15)

deli_top_items_plot = plotBarGraph(bar_data = deli_top_items, 
                                   plot_title = "Deli Top Sellers",
                                   x_var = deli_top_items$Menu.Item, 
                                   x_lab = "Deli Item",
                                   y_var = deli_top_items$Item.Qty,
                                   y_lab = "Qty Sold")
savePlot(reportName = "Deli_Top_Sellers", report = deli_top_items_plot)
all_plots = c(all_plots, deli_top_items_plot)

deli_top_netters = deli_items %>%
  arrange(desc(Net.Amount)) %>%
  head(n=15)

## it would be nice to find the margin for N/A or at least the costs :////
deli_top_netters_plot = plotBarGraph(bar_data = deli_top_netters, 
                                     plot_title = "Deli Top Netters",
                                     x_var = deli_top_netters$Menu.Item, 
                                     x_lab = "Deli Item",
                                     y_var = deli_top_netters$Net.Amount,
                                     y_lab = "Net Amount")
savePlot(reportName = "Deli_Top_Netters", report = deli_top_netters_plot)
all_plots = c(all_plots, deli_top_netters_plot)


